version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: gameoflife-neo4j
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      # Authentication settings
      NEO4J_AUTH: neo4j/gameoflife123
      
      # Performance settings
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 512m
      
      # Security settings
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      
      # Logging
      NEO4J_dbms_logs_debug_level: INFO
      
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    
    networks:
      - gameoflife-network
    
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p gameoflife123 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  gameoflife-network:
    driver: bridge